name: CI Ubuntu Jammy (Devcontainer)

on:
  repository_dispatch:
    types:
    - build-jammy
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  run:
    runs-on: ubuntu-22.04
    steps:
    - name: Maximize build space
      shell: bash
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo docker image prune --all --force
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Pre-build dev container image
      uses: devcontainers/ci@v0.3
      with:
        # FIXME: use mc-rtc/mc-rtc-superbuild before merging
        # Not supported to be pushed to from forks
        #imageName: ghcr.io/mc-rtc/mc-rtc-superbuild
        imageName: ghcr.io/arntanguy/mc-rtc-superbuild
        imageTag: jammy
        subFolder: .github/devcontainer/ubuntu-22.04
        configFile: .github/devcontainer/ubuntu-22.04/devcontainer.json
        cacheFrom: ghcr.io/arntanguy/mc-rtc-superbuild
        push: always
